---
- name: Restart k3s
  ansible.builtin.service:
    name: k3s
    state: restarted
  when: inventory_hostname in groups['master']

- name: Restart k3s-agent
  ansible.builtin.service:
    name: k3s-agent
    state: restarted
  when: inventory_hostname in groups['worker']
